helm: add helm tutorial
nodeshift/tutorial pull request #12
Opened 2021-09-27 15:04 UTC by AshCripps

2021-11-02 14:38 UTC, mhdawson commented on helm/README.md
> +The application you will use is the one created in the previous tutorial - https://github.com/nodeshift/mern-workshop
```suggestion
The application you will use is the one created in the previous tutorial - https://github.com/nodeshift/mern-workshop
```

2021-11-02 14:39 UTC, mhdawson commented on helm/README.md
> +Before getting started, make sure you have the following prerequisites installed on your system.
Maybe I already asked this, but would it be possible to use the sandbox instead of a local install?

2021-11-02 14:48 UTC, mhdawson commented on helm/README.md
> +   The rest of the fields are self explanatory but lets add some more information to describe our chart. We are going to set a Kubernetes minimum version, add some descriptive keywords and add our na
Does it matter where the additional yml is added? If it needs to be at the end instead of the front that might make sense to say.

2021-11-02 14:52 UTC, mhdawson commented on helm/README.md
> +    repository: https://charts.bitnami.com/bitnami
```suggestion
     version: 5.0.2
     repository: https://charts.bitnami.com/bitnami
```

2021-11-02 14:54 UTC, mhdawson commented on helm/README.md
> +$ rm myapp/templates/*
```suggestion
$ rm -rf myapp/templates/*
```

2021-11-02 14:56 UTC, mhdawson commented on helm/README.md
> +Our third file will spawn the service for the backend part of our application. Create a file called `chart/myapp/templates/backend-service.yaml` and paste in the following:
Maybe we should remove `chart` from the path here as it was not in the previous line removing the templates

2021-11-02 14:58 UTC, mhdawson commented on helm/README.md
> +What this create will the service that serves our frontend and allows for it to be connected to the outside world. `nodePort` is the port we want our service to be accessible through so `localhost:30
```suggestion
This will create the service that serves our frontend and allows for it to be connected to the outside world. `nodePort` is the port we want our service to be accessible through so `localhost:30444` will take us to our frontend once deployed
```

2021-11-02 15:01 UTC, mhdawson commented on helm/README.md
> +For the `values.yaml` file we are going to split it in 3 sections, have a read of each section and then add them all to your `values.yaml` file
Since we specified the path for the other files we should probably include it here as well.

2021-11-02 15:07 UTC, mhdawson commented on helm/README.md
> +$ docker build -f backend/Dockerfile -t backend:v1.0.0 backend
@AshCripps if you've already updated, I think its still missing the instructions for cloning  https://github.com/nodeshift/mern-workshop and being in the right place to run the comments.

2021-11-02 15:30 UTC, mhdawson commented on helm/README.md
> +You have now created a Helm Chart which deploys a frontend and a backend whilst also calling and installing a dependency chart from the internet.
Maybe add a link here to the doc in the mern tutorial that shows how to test out the running app and possibly a few paragraphs running kubectl commands to look at the deployed pods?

2021-11-02 17:04 UTC, AshCripps commented on helm/README.md
> +Before getting started, make sure you have the following prerequisites installed on your system.
It probably can but I thought we werent going to promote the sandbox in this tutorial.

2021-11-02 19:31 UTC, mhdawson commented on helm/README.md
> +Before getting started, make sure you have the following prerequisites installed on your system.
I guess I just come back to it knowing how tricky/time consuming setting up kube can be, especially if people don't want to add to the config on their machine.  That might not help completely in this case though since they'd still need docker and helm installed locally.

2021-11-02 20:23 UTC, mhdawson commented on helm/README.md
> +Kubernetes 1.16, so make sure to run with 1.14.7.
I don't think this part is right since it later requires a newer version of kube

2021-11-02 20:52 UTC, mhdawson commented on helm/README.md
> +     version: 5.0.2
This did not work for me. I had to upgrade kube to pass the kubeVersion line added above. After a while I believe I then figured out that for 5.0.2 helm failed the install with the complaint:

```
Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "Deployment" in version "extensions/v1beta1"
```



```

2021-11-02 20:52 UTC, mhdawson commented on helm/README.md
> +     version: 5.0.2
I've updated to 10.0.0 for the mondodb version, and it installs, I can hit the app but it does not add items to the todo list

2021-11-02 22:21 UTC, mhdawson commented on helm/README.md
> +     version: 5.0.2
Seems like some of the options changed, added comment to update values for mongodb and its working now

2021-11-02 22:21 UTC, mhdawson commented on helm/README.md
> +  replicaSet.replicas.secondary: 3
```suggestion
mongodb:
  auth:
    enabled: false
  replicaSet.enabled: true
  service.type: LoadBalancer
  replicaSet.replicas.secondary: 3
```

2021-11-02 22:23 UTC, mhdawson commented on helm/README.md
> +  replicaSet.replicas.secondary: 3
I think the parameters were not taking effect as `mongo` needs to match `mongodb` as that is the name of the dependency in the Chart.yaml file.

In addition for newer version of mongodb usePassword was replaced with the auth.enabled as show in the change.

2021-11-02 22:25 UTC, mhdawson commented on helm/README.md
> +     version: 5.0.2
```suggestion
     version: 10.0.0
```

2021-11-02 22:25 UTC, mhdawson commented on helm/README.md
> +     version: 5.0.2
Note it also seems to work with 8.0.0 if 10.0.0 is too recent for some reason on other platforms.

2021-11-23 14:13 UTC, BethGriggs commented on helm/README.md
> +- Create liveiness probes
```suggestion
- Create liveness probes
```

2021-11-23 14:13 UTC, BethGriggs commented on helm/README.md
> +This will create the following filestructure:
```suggestion
This will create the following file structure:
```

2021-11-23 14:13 UTC, BethGriggs commented on helm/README.md
> +These files will form the basis of your Helm Chart, lets explore the precreated files and make some nessacary changes
```suggestion
These files will form the basis of your Helm Chart, lets explore the pre-created files and make some necessary changes.
```

2021-11-23 14:13 UTC, BethGriggs commented on helm/README.md
> +   This file works the same as any .ignore file, you just fill in the patterns you don't want to be packaged up into the helm chart. For example if you have some secrets saved as a JSON file that you
```suggestion
This file works the same as any .ignore file, you just fill in the patterns you don't want to be packaged up into the helm chart. For example, if you have some secrets saved as a JSON file that you don not want to be inside the helm chart. For our application we dont not have any files we need to protect so let's move on to the next step.
```

2021-11-23 14:13 UTC, BethGriggs commented on helm/README.md
> +   `version` is the charts version, increment this under semver everytime you update the chart
```suggestion
   `version` is the charts version, increment this under semver every time you update the chart
```

2021-11-23 14:13 UTC, BethGriggs commented on helm/README.md
> +   `appVersion` is the version of the app you are deploying, this is to be increased everytime you increase the version of your app but does not impact the charts version
```suggestion
   `appVersion` is the version of the app you are deploying, this is to be increased every time you increase the version of your app but does not impact the charts version 
```

2021-11-23 14:13 UTC, BethGriggs commented on helm/README.md
> +   The rest of the fields are self explanatory but lets add some more information to describe our chart. We are going to set a Kubernetes minimum version, add some descriptive keywords and add our na
```suggestion
   The rest of the fields are self-explanatory but let's add some more information to describe our chart. We are going to set a Kubernetes minimum version, add some descriptive keywords and add our name as Maintainers. So go ahead and add the following to your `Chart.yaml` whilst substituting your name and email in:
```

2021-11-23 14:13 UTC, BethGriggs commented on helm/README.md
> +   The final key thing we are going to add is a dependecy, our application needs mongoDB to run so we are going to call a premade mongo chart to install mongo as we install our chart. Firstly we need
```suggestion
   The final key thing we are going to add is a dependency, our application needs mongoDB to run so we are going to call an existing mongo chart to install mongo as we install our chart. Firstly we need to add to our `Chart.yaml`:
```

2021-11-23 14:13 UTC, BethGriggs commented on helm/README.md
> +   Then run the following command in terminal to download the chart:
```suggestion
   Then run the following command in the terminal to download the chart:
```

2021-11-23 14:13 UTC, BethGriggs commented on helm/README.md
> +These files represent the kubernetes objects that our Helm Chart will deploy - you can set up the deployment and service, and you can also create a serviceaccount for your app to use. The `NOTES.txt`
```suggestion
These files represent the kubernetes objects that our Helm Chart will deploy - you can set up the deployment and service, and you can also create a serviceaccount for your app to use. The `NOTES.txt` file is just the notes that will be displayed to the user when they deploy your Helm Chart, you can use this to provide further instruction to them to get your application working. `_helpers.tpl` is where template helpers that you can re-use throughout the chart go. However for this tutorial we are going to use our own files so you can go ahead and remove the generated files:
```

2021-11-23 14:13 UTC, BethGriggs commented on helm/README.md
> +Now lets move on to making our own template files!
```suggestion
Now let's move on to making our own template files!
```

2021-11-23 14:13 UTC, BethGriggs commented on helm/README.md
> +The first template we will create will deploy the service for our frontend. Lets create a file called `chart/myapp/templates/frontend-service.yaml` and paste in the following:
```suggestion
The first template we will create will deploy the service for our frontend. Let's create a file called `chart/myapp/templates/frontend-service.yaml` and paste in the following:
```

2021-11-23 14:13 UTC, BethGriggs commented on helm/README.md
> +For the `chart/myapp/values.yaml` file we are going to split it in 3 sections, have a read of each section and then add them all to your `values.yaml` file
```suggestion
For the `chart/myapp/values.yaml` file we are going to split it into 3 sections, have a read of each section and then add them all to your `values.yaml` file
```

2021-11-23 15:16 UTC, BethGriggs requested changes

2021-11-23 15:16 UTC, BethGriggs commented on helm/README.md
> +You have now created a Helm Chart which deploys a frontend and a backend whilst also calling and installing a dependency chart from the internet.
Agreed, we need the `kubectl get pods` steps to demonstrate the three pods the Helm chart has created. And then it'd be good to instruct the user how to access the frontend and add an item to the todo list that is persisted in MongoDB (just to prove the end-to-end flow).

2021-12-10 17:09 UTC, BethGriggs approved these changes

2021-12-10 17:35 UTC, mhdawson approved these changes
LGTM

2021-12-10 17:43 UTC, merged