Microk8s flow pass through - Application interaction
nodeshift/tutorial pull request #16
Opened 2022-01-26 13:38 UTC by pacostas

2022-02-14 15:53 UTC, BethGriggs requested changes

2022-02-14 15:53 UTC, BethGriggs commented on helm/README.md
> +      url: myapp-mongodb
This change makes the whole flow work for me using Docker for Desktop 🎉

2022-02-14 16:51 UTC, pacostas commented on helm/README.md
> +#### Microk8s
* the `sudo usermod -a -G microk8s ibmuser` I dont think its necessary, at least is not included on the install instructions visit https://microk8s.io/ -> click on linux box 
* `sudo microk8s.start` From the installation tutorial seems that the microk8s, starts after installing it. In any case this command exists a little bit lower, on the enable the private registry section, so its duplicate.
* `sudo snap alias microk8s.kubectl kubectl` this alias I decided to remove it cause some users might get confused and start using the configuration of kubectl instead of microk8s, this will prevent them cause kubectl wont exist on the system and will throw them a command not found. We can keep it, but I would suggest adding it at the end of the tutorial, something like a tips section.
* `export PATH=/snap/bin:$PATH` This one is for exposing snap in the PATH. I dont think its relevant on these steps in a first place. We can add a new section for installing snap in case it is not installed as is here https://snapcraft.io/docs/installing-snapd, where this command would make sense but still, its not necessary cause package manage handles to export it on the path anyway.
*  `sudo microk8s.config >~/.kube/config` I dont know why this command is being used. I dont see a reason exporting  configuration for kubectl where kubectl is not installed.
* `microk8s.enable dns registry` this one has been replaced with this one `microk8s enable dashboard dns registry istio`

But the main reason that this wont work properly on the tutorial is that it does not enable private registry. Enabling registry is covered officially here https://microk8s.io/docs/registry-private . Enabling registry (which varies by microk8s version) is covered on the tutorial without visiting this link.

2022-02-14 17:00 UTC, pacostas commented on helm/README.md
> +   microk8s helm3 dependency update
I agree. Yes, that is possible by using an alias. Another solution is to use `helm` Instead of `microk8s helm3` (I figure it out few days ago) that way we also avoid the alias and the only change on the tutorial would be simply deleting the second set of commands, I have to test this one in order to update the docs.

2022-02-14 17:05 UTC, pacostas commented on helm/README.md
> +      url: myapp-mongodb
Which one did you use? `mongo-mongodb` or `myapp-mongodb`

2022-02-23 10:31 UTC, pacostas commented on helm/README.md
> +#### Microk8s
* I replaced the `sudo usermod -a -G microk8s ibmuser` with `sudo usermod -a -G microk8s $USER sudo chown -f -R $USER ~/.kube`
* I have set that the end `sudo microk8s.start` of the installation
* I added the alias `sudo snap alias microk8s.kubectl kubectl` as you mentioned. In the past, I decided to remove it cause some users might got confused and start using the configuration of kubectl instead of microk8s, this would prevent them cause kubectl wont exist on their system and would throw them a command not found error. This tactic might not being necessary I think.
* the `export PATH=/snap/bin:$PATH` is not necessary because during snap installation, package manager exports it on the env var
* this wont work `microk8s.enable dns registry` and a new section "3.Enable private registry for Microk8s" has been added instead

2022-02-23 10:32 UTC, pacostas commented on helm/README.md
> +   microk8s helm3 dependency update
Ok, tested and helm works properly.

2022-02-23 11:47 UTC, BethGriggs commented on helm/README.md
> +    sudo snap install microk8s --classic
Not sure this first command needs `sudo`? It didn't before

2022-02-23 11:52 UTC, BethGriggs commented on helm/README.md
> +
I think another series of commands here, so the user can see the request reached the backend

2022-02-23 13:13 UTC, pacostas commented on helm/README.md
> +    sudo snap install microk8s --classic
If sudo is not added, it prompts you for authentication. Yes, we can remove it and it will still work. On the https://microk8s.io/ -> "clicking on the penguin" suggests on using the sudo

2022-02-23 15:52 UTC, BethGriggs commented on helm/README.md
> +    sudo snap install microk8s --classic
No worries, we can just follow the official docs.

2022-02-28 11:54 UTC, BethGriggs approved these changes

2022-02-28 12:49 UTC, merged